//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string Count { get; set; }
        public int Unit { get; set; }
        public string ProductNote { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual Image Image1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
